# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedded-protocol/embedded_sass.proto

require "google/protobuf"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("embedded-protocol/embedded_sass.proto", syntax: :proto3) do
    add_message "sass.embedded_protocol.InboundMessage" do
      oneof :message do
        optional :compileRequest, :message, 2, "sass.embedded_protocol.InboundMessage.CompileRequest"
        optional :canonicalizeResponse, :message, 3, "sass.embedded_protocol.InboundMessage.CanonicalizeResponse"
        optional :importResponse, :message, 4, "sass.embedded_protocol.InboundMessage.ImportResponse"
        optional :fileImportResponse, :message, 5, "sass.embedded_protocol.InboundMessage.FileImportResponse"
        optional :functionCallResponse, :message, 6, "sass.embedded_protocol.InboundMessage.FunctionCallResponse"
      end
    end
    add_message "sass.embedded_protocol.InboundMessage.CompileRequest" do
      optional :id, :uint32, 1
      optional :style, :enum, 4, "sass.embedded_protocol.InboundMessage.CompileRequest.OutputStyle"
      optional :source_map, :bool, 5
      repeated :importers, :message, 6, "sass.embedded_protocol.InboundMessage.CompileRequest.Importer"
      repeated :global_functions, :string, 7
      oneof :input do
        optional :string, :message, 2, "sass.embedded_protocol.InboundMessage.CompileRequest.StringInput"
        optional :path, :string, 3
      end
    end
    add_message "sass.embedded_protocol.InboundMessage.CompileRequest.StringInput" do
      optional :source, :string, 1
      optional :url, :string, 2
      optional :syntax, :enum, 3, "sass.embedded_protocol.InboundMessage.Syntax"
      optional :importer, :message, 4, "sass.embedded_protocol.InboundMessage.CompileRequest.Importer"
    end
    add_message "sass.embedded_protocol.InboundMessage.CompileRequest.Importer" do
      oneof :importer do
        optional :path, :string, 1
        optional :importer_id, :uint32, 2
        optional :file_importer_id, :uint32, 3
      end
    end
    add_enum "sass.embedded_protocol.InboundMessage.CompileRequest.OutputStyle" do
      value :EXPANDED, 0
      value :COMPRESSED, 1
      value :NESTED, 2
      value :COMPACT, 3
    end
    add_message "sass.embedded_protocol.InboundMessage.CanonicalizeResponse" do
      optional :id, :uint32, 1
      oneof :result do
        optional :url, :string, 2
        optional :error, :string, 3
      end
    end
    add_message "sass.embedded_protocol.InboundMessage.ImportResponse" do
      optional :id, :uint32, 1
      oneof :result do
        optional :success, :message, 2, "sass.embedded_protocol.InboundMessage.ImportResponse.ImportSuccess"
        optional :error, :string, 3
      end
    end
    add_message "sass.embedded_protocol.InboundMessage.ImportResponse.ImportSuccess" do
      optional :contents, :string, 1
      optional :syntax, :enum, 2, "sass.embedded_protocol.InboundMessage.Syntax"
      optional :sourceMapUrl, :string, 3
    end
    add_message "sass.embedded_protocol.InboundMessage.FileImportResponse" do
      optional :id, :uint32, 1
      oneof :result do
        optional :file_url, :string, 2
        optional :error, :string, 3
      end
    end
    add_message "sass.embedded_protocol.InboundMessage.FunctionCallResponse" do
      optional :id, :uint32, 1
      oneof :result do
        optional :success, :message, 2, "sass.embedded_protocol.Value"
        optional :error, :string, 3
      end
    end
    add_enum "sass.embedded_protocol.InboundMessage.Syntax" do
      value :SCSS, 0
      value :INDENTED, 1
      value :CSS, 2
    end
    add_message "sass.embedded_protocol.OutboundMessage" do
      oneof :message do
        optional :error, :message, 1, "sass.embedded_protocol.ProtocolError"
        optional :compileResponse, :message, 2, "sass.embedded_protocol.OutboundMessage.CompileResponse"
        optional :logEvent, :message, 3, "sass.embedded_protocol.OutboundMessage.LogEvent"
        optional :canonicalizeRequest, :message, 4, "sass.embedded_protocol.OutboundMessage.CanonicalizeRequest"
        optional :importRequest, :message, 5, "sass.embedded_protocol.OutboundMessage.ImportRequest"
        optional :fileImportRequest, :message, 6, "sass.embedded_protocol.OutboundMessage.FileImportRequest"
        optional :functionCallRequest, :message, 7, "sass.embedded_protocol.OutboundMessage.FunctionCallRequest"
      end
    end
    add_message "sass.embedded_protocol.OutboundMessage.CompileResponse" do
      optional :id, :int32, 1
      oneof :result do
        optional :success, :message, 2, "sass.embedded_protocol.OutboundMessage.CompileResponse.CompileSuccess"
        optional :failure, :message, 3, "sass.embedded_protocol.OutboundMessage.CompileResponse.CompileFailure"
      end
    end
    add_message "sass.embedded_protocol.OutboundMessage.CompileResponse.CompileSuccess" do
      optional :css, :string, 1
      optional :source_map, :string, 2
    end
    add_message "sass.embedded_protocol.OutboundMessage.CompileResponse.CompileFailure" do
      optional :message, :string, 1
      optional :span, :message, 2, "sass.embedded_protocol.SourceSpan"
      optional :stack_trace, :string, 3
    end
    add_message "sass.embedded_protocol.OutboundMessage.LogEvent" do
      optional :compilation_id, :uint32, 1
      optional :type, :enum, 2, "sass.embedded_protocol.OutboundMessage.LogEvent.Type"
      optional :message, :string, 3
      optional :span, :message, 4, "sass.embedded_protocol.SourceSpan"
      optional :stack_trace, :string, 5
    end
    add_enum "sass.embedded_protocol.OutboundMessage.LogEvent.Type" do
      value :WARNING, 0
      value :DEPRECATION_WARNING, 1
      value :DEBUG, 2
    end
    add_message "sass.embedded_protocol.OutboundMessage.CanonicalizeRequest" do
      optional :id, :uint32, 1
      optional :compilation_id, :uint32, 2
      optional :importer_id, :uint32, 3
      optional :url, :string, 4
    end
    add_message "sass.embedded_protocol.OutboundMessage.ImportRequest" do
      optional :id, :uint32, 1
      optional :compilation_id, :uint32, 2
      optional :importer_id, :uint32, 3
      optional :url, :string, 4
    end
    add_message "sass.embedded_protocol.OutboundMessage.FileImportRequest" do
      optional :id, :uint32, 1
      optional :compilation_id, :uint32, 2
      optional :importer_id, :uint32, 3
      optional :url, :string, 4
    end
    add_message "sass.embedded_protocol.OutboundMessage.FunctionCallRequest" do
      optional :id, :uint32, 1
      optional :compilation_id, :uint32, 2
      repeated :arguments, :message, 5, "sass.embedded_protocol.Value"
      oneof :identifier do
        optional :name, :string, 3
        optional :function_id, :uint32, 4
      end
    end
    add_message "sass.embedded_protocol.ProtocolError" do
      optional :type, :enum, 1, "sass.embedded_protocol.ProtocolError.ErrorType"
      optional :id, :int32, 2
      optional :message, :string, 3
    end
    add_enum "sass.embedded_protocol.ProtocolError.ErrorType" do
      value :PARSE, 0
      value :PARAMS, 1
      value :INTERNAL, 2
    end
    add_message "sass.embedded_protocol.SourceSpan" do
      optional :text, :string, 1
      optional :start, :message, 2, "sass.embedded_protocol.SourceSpan.SourceLocation"
      optional :end, :message, 3, "sass.embedded_protocol.SourceSpan.SourceLocation"
      optional :url, :string, 4
      optional :context, :string, 5
    end
    add_message "sass.embedded_protocol.SourceSpan.SourceLocation" do
      optional :offset, :uint32, 1
      optional :line, :uint32, 2
      optional :column, :uint32, 3
    end
    add_message "sass.embedded_protocol.Value" do
      oneof :value do
        optional :string, :message, 1, "sass.embedded_protocol.Value.String"
        optional :number, :message, 2, "sass.embedded_protocol.Value.Number"
        optional :rgb_color, :message, 3, "sass.embedded_protocol.Value.RgbColor"
        optional :hsl_color, :message, 4, "sass.embedded_protocol.Value.HslColor"
        optional :list, :message, 5, "sass.embedded_protocol.Value.List"
        optional :map, :message, 6, "sass.embedded_protocol.Value.Map"
        optional :singleton, :enum, 7, "sass.embedded_protocol.Value.Singleton"
        optional :compiler_function, :message, 8, "sass.embedded_protocol.Value.CompilerFunction"
        optional :host_function, :message, 9, "sass.embedded_protocol.Value.HostFunction"
      end
    end
    add_message "sass.embedded_protocol.Value.String" do
      optional :text, :string, 1
      optional :quoted, :bool, 2
    end
    add_message "sass.embedded_protocol.Value.Number" do
      optional :value, :double, 1
      repeated :numerators, :string, 2
      repeated :denominators, :string, 3
    end
    add_message "sass.embedded_protocol.Value.RgbColor" do
      optional :red, :uint32, 1
      optional :green, :uint32, 2
      optional :blue, :uint32, 3
      optional :alpha, :double, 4
    end
    add_message "sass.embedded_protocol.Value.HslColor" do
      optional :hue, :double, 1
      optional :saturation, :double, 2
      optional :lightness, :double, 3
      optional :alpha, :double, 4
    end
    add_message "sass.embedded_protocol.Value.List" do
      optional :separator, :enum, 1, "sass.embedded_protocol.Value.List.Separator"
      optional :has_brackets, :bool, 2
      repeated :contents, :message, 3, "sass.embedded_protocol.Value"
    end
    add_enum "sass.embedded_protocol.Value.List.Separator" do
      value :COMMA, 0
      value :SPACE, 1
      value :SLASH, 2
      value :UNDECIDED, 3
    end
    add_message "sass.embedded_protocol.Value.Map" do
      repeated :entries, :message, 1, "sass.embedded_protocol.Value.Map.Entry"
    end
    add_message "sass.embedded_protocol.Value.Map.Entry" do
      optional :key, :message, 1, "sass.embedded_protocol.Value"
      optional :value, :message, 2, "sass.embedded_protocol.Value"
    end
    add_message "sass.embedded_protocol.Value.CompilerFunction" do
      optional :id, :uint32, 1
    end
    add_message "sass.embedded_protocol.Value.HostFunction" do
      optional :id, :uint32, 1
      optional :signature, :string, 2
    end
    add_enum "sass.embedded_protocol.Value.Singleton" do
      value :TRUE, 0
      value :FALSE, 1
      value :NULL, 2
    end
  end
end

module Sass
  module EmbeddedProtocol
    InboundMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.InboundMessage").msgclass
    InboundMessage::CompileRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.InboundMessage.CompileRequest").msgclass
    InboundMessage::CompileRequest::StringInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.InboundMessage.CompileRequest.StringInput").msgclass
    InboundMessage::CompileRequest::Importer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.InboundMessage.CompileRequest.Importer").msgclass
    InboundMessage::CompileRequest::OutputStyle = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.InboundMessage.CompileRequest.OutputStyle").enummodule
    InboundMessage::CanonicalizeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.InboundMessage.CanonicalizeResponse").msgclass
    InboundMessage::ImportResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.InboundMessage.ImportResponse").msgclass
    InboundMessage::ImportResponse::ImportSuccess = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.InboundMessage.ImportResponse.ImportSuccess").msgclass
    InboundMessage::FileImportResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.InboundMessage.FileImportResponse").msgclass
    InboundMessage::FunctionCallResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.InboundMessage.FunctionCallResponse").msgclass
    InboundMessage::Syntax = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.InboundMessage.Syntax").enummodule
    OutboundMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.OutboundMessage").msgclass
    OutboundMessage::CompileResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.OutboundMessage.CompileResponse").msgclass
    OutboundMessage::CompileResponse::CompileSuccess = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.OutboundMessage.CompileResponse.CompileSuccess").msgclass
    OutboundMessage::CompileResponse::CompileFailure = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.OutboundMessage.CompileResponse.CompileFailure").msgclass
    OutboundMessage::LogEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.OutboundMessage.LogEvent").msgclass
    OutboundMessage::LogEvent::Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.OutboundMessage.LogEvent.Type").enummodule
    OutboundMessage::CanonicalizeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.OutboundMessage.CanonicalizeRequest").msgclass
    OutboundMessage::ImportRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.OutboundMessage.ImportRequest").msgclass
    OutboundMessage::FileImportRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.OutboundMessage.FileImportRequest").msgclass
    OutboundMessage::FunctionCallRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.OutboundMessage.FunctionCallRequest").msgclass
    ProtocolError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.ProtocolError").msgclass
    ProtocolError::ErrorType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.ProtocolError.ErrorType").enummodule
    SourceSpan = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.SourceSpan").msgclass
    SourceSpan::SourceLocation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.SourceSpan.SourceLocation").msgclass
    Value = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.Value").msgclass
    Value::String = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.Value.String").msgclass
    Value::Number = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.Value.Number").msgclass
    Value::RgbColor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.Value.RgbColor").msgclass
    Value::HslColor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.Value.HslColor").msgclass
    Value::List = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.Value.List").msgclass
    Value::List::Separator = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.Value.List.Separator").enummodule
    Value::Map = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.Value.Map").msgclass
    Value::Map::Entry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.Value.Map.Entry").msgclass
    Value::CompilerFunction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.Value.CompilerFunction").msgclass
    Value::HostFunction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.Value.HostFunction").msgclass
    Value::Singleton = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sass.embedded_protocol.Value.Singleton").enummodule
  end
end
